CREATE TABLE IF NOT EXISTS boards (
    board_id INTEGER PRIMARY KEY NOT NULL,
    description TEXT NOT NULL DEFAULT "",
    name VARCHAR(250) NOT NULL,
    position INTEGER NOT NULL, 
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);